### ISSUE TITLE
 截图出错

### ISSUE THREAD

**Issue by liuzj288** [lgc2333/nonebot-plugin-bawiki#1]
![image](https://user-images.githubusercontent.com/13833404/183423469-dd05da88-4db6-4a09-8a31-dde7c84ccb87.png)

**Comment by lgc2333** [comment]
访问网页超时了，再试试看

从 Windows 版邮件发送

发件人: liuzj288
发送时间: 2022年8月8日 20:58
收件人: lgc2333/nonebot-plugin-bawiki
抄送: Subscribed
主题: [lgc2333/nonebot-plugin-bawiki] 截图出错 (Issue #1)

**Comment by lgc2333** [comment]
更新一下试试看，或许解决了
