### ISSUE TITLE
nonebot客户端与插件依赖包版本冲突

### ISSUE THREAD

**Issue by Rouphy** [lgc2333/nonebot-plugin-bawiki#10]
nb-cli安装插件时报错

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyinquirer 1.0.3 requires prompt_toolkit==1.0.14, but you have prompt-toolkit 3.0.31 which is incompatible.
```

尝试pip install prompt_toolkit==1.0.14后报错

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyinquirer 1.0.3 requires prompt_toolkit==1.0.14, but you have prompt-toolkit 3.0.31 which is incompatible.
```

**Comment by lgc2333** [comment]
`pip install -U prompt_toolkit==1.0.14`试试

**Comment by lgc2333** [comment]
本插件并没有依赖该包，请检查其他插件2022年10月7日 下午6:20，Rouphy ***@***.***>写道：

nb-cli安装插件时报错

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

pyinquirer 1.0.3 requires prompt_toolkit==1.0.14, but you have prompt-toolkit 3.0.31 which is incompatible.



尝试pip install prompt_toolkit==1.0.14后报错

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

pyinquirer 1.0.3 requires prompt_toolkit==1.0.14, but you have prompt-toolkit 3.0.31 which is incompatible.
