### ISSUE TITLE
新学生wiki词条停止了

### ISSUE THREAD

**Issue by Aobaaaa** [lgc2333/nonebot-plugin-bawiki#12]
你好，用ba新学生指令，截下来的图显示，wiki那边有新的“当期UP”词条，原新学生词条停止维护了。
请问有其他办法能查看新的学生嘛
![image](https://user-images.githubusercontent.com/106361074/196030072-7c390d0b-3c0b-4863-9d1b-bb7243f8ff90.png)

**Comment by lgc2333** [comment]
> 你好，用ba新学生指令，截下来的图显示，wiki那边有新的“当期UP”词条，原新学生词条停止维护了。 请问有其他办法能查看新的学生嘛 ![image](https://user-images.githubusercontent.com/106361074/196030072-7c390d0b-3c0b-4863-9d1b-bb7243f8ff90.png)

今晚尝试一下

**Comment by lgc2333** [comment]
昨天更新的b3版本，把shcaledb的日程表从网页截图改成了Pillow画图，里面有国际服和日服的当期up，不知道这样能不能满足你

触发指令: `ba日程表schale`

**Comment by Aobaaaa** [comment]
> 昨天更新的b3版本，把shcaledb的日程表从网页截图改成了Pillow画图，里面有国际服和日服的当期up，不知道这样能不能满足你
> 
> 触发指令: `ba日程表schale`

可以的，非常感谢

**Comment by lgc2333** [comment]
今天新增了指令`ba国际服千里眼`，不知道能否帮到你
