### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by Aobaaaa** [lgc2333/nonebot-plugin-bawiki#14]
![L}O{(416S{D 5DKKEMWINUW](https://user-images.githubusercontent.com/106361074/196909411-6a6c1bc5-928a-48af-ae60-9dd8c95c9283.png)

**Comment by lgc2333** [comment]
草 这是py3.10专有语法，稍等fix
(没有发release的版本不确保可用性，当然发了也不一定(((

**Comment by Aobaaaa** [comment]
> 草 这是py3.10专有语法，稍等fix (没有发release的版本不确保可用性，当然发了也不一定(((

原来如此，那我用回上个版本吧

**Comment by lgc2333** [comment]
> > 草 这是py3.10专有语法，稍等fix (没有发release的版本不确保可用性，当然发了也不一定(((
> 
> 原来如此，那我用回上个版本吧

刚刚修了

**Comment by Aobaaaa** [comment]
> > > 草 这是py3.10专有语法，稍等fix (没有发release的版本不确保可用性，当然发了也不一定(((
> > 
> > 
> > 原来如此，那我用回上个版本吧
> 
> 刚刚修了

好的感谢！

**Comment by Aobaaaa** [comment]
> > > 草 这是py3.10专有语法，稍等fix (没有发release的版本不确保可用性，当然发了也不一定(((
> > 
> > 
> > 原来如此，那我用回上个版本吧
> 
![)8 %RACP)HH13C{{J$P8~5I](https://user-images.githubusercontent.com/106361074/196912156-a4e93dfe-e141-47b0-aefc-2c2eb09b2ae2.png)

> 刚刚修了



> > > 草 这是py3.10专有语法，稍等fix (没有发release的版本不确保可用性，当然发了也不一定(((
> > 
> > 
> > 原来如此，那我用回上个版本吧
> 
> 刚刚修了

![Uploading )8[%RACP)HH13C{{J$P8~5I.png…]()
好像出现新的问题了（

**Comment by lgc2333** [comment]
应该已经全部修复，等会发release

**Comment by Aobaaaa** [comment]
> 应该已经全部修复，等会发release

已经成功加载了，非常感谢！
