### ISSUE TITLE
萌娘百科又寄了，增加个参数改成获取到词条链接直接截图吧

### ISSUE THREAD

**Issue by liuzj288** [lgc2333/nonebot-plugin-bawiki#15]
![image](https://user-images.githubusercontent.com/13833404/197737640-ba16f1dc-e708-4443-9548-b5ae6a8955d5.png)

**Comment by lgc2333** [comment]
详细说下这是哪个功能

**Comment by lgc2333** [comment]
而且直接截图有的人会超时，所以不打算搞成直接截图

**Comment by lgc2333** [comment]
azzzzzzzzzzz你发错仓库了吧
