### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by LHT114514** [lgc2333/nonebot-plugin-bawiki#17]
加载插件时提示Task exception was never retrieved
![pic-1](https://user-images.githubusercontent.com/121667105/210180637-cc91d7c0-609f-47a0-9f04-5c349f07ee29.png)
![pic-2](https://user-images.githubusercontent.com/121667105/210180639-9daf8054-ff23-4138-8f9d-6df3c9295d24.png)

**Comment by lgc2333** [comment]
关掉FASTAPI_RELOAD
https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi_reload

**Comment by LHT114514** [comment]
问题解决了，谢谢
