### ISSUE TITLE
绘制日程表图片出错

### ISSUE THREAD

**Issue by sylviezip** [lgc2333/nonebot-plugin-bawiki#18]
![R@W9F5I1U~KDABR9A{1 I1K](https://user-images.githubusercontent.com/76864564/215338389-fb5c469a-c8b9-4643-a584-e50faff0f53b.jpg)
情况复现：在某个QQ群输入`ba日程表`，期望结果应该是正常打印图片，实际上会输出**绘制日程表图片出错，请检查后台输出**，和issue#16 貌似是不同的错误
#16

**Comment by lgc2333** [comment]
不会imageutils又改了什么吧 麻了

**Comment by lgc2333** [comment]
妈的 还真改了

**Comment by lgc2333** [comment]
发版了，再试试

**Comment by sylviezip** [comment]
解决了，可以输出正常的结果，赞美大佬！
