### ISSUE TITLE
提几个小建议吧

### ISSUE THREAD

**Issue by Hei-Qiang** [lgc2333/nonebot-plugin-bawiki#2]
1.日程表希望能做出国际服和日服的区分
2.学生查询希望能做出常用外号的查询，比如大叔和水大叔、春月、fes这种的
3.个人参考了其他的几个BA机器人，要是能添加以下功能就更好了：羁绊等级（查询角色多少级羁绊解锁live2D，可以图片输出）、千里眼（看卡池）

希望作者大大加油，很不错的插件呢！

**Comment by lgc2333** [comment]
别名打算做，国际服日程表的话这边我没有数据源没法整，然后开学了要咕比较长时间2022年8月9日 上午10:23，Hei-Qiang ***@***.***>写道：
1.日程表希望能做出国际服和日服的区分
2.学生查询希望能做出常用外号的查询，比如大叔和水大叔、春月、fes这种的
3.个人参考了其他的几个BA机器人，要是能添加以下功能就更好了：羁绊等级（查询角色多少级羁绊解锁live2D，可以图片输出）、千里眼（看卡池）
希望作者大大加油，很不错的插件呢！

**Comment by lgc2333** [comment]
可以帮忙扩充插件的学生别名字典么qwq 感谢了

方式写在readme里了

**Comment by lgc2333** [comment]
把别名字典弄完就可以发布下个版本了

**Comment by ILYSHL** [comment]
国际服的数据的话参考[Hoshino的BA插件](https://github.com/Cosmos01/Blue_Archive_HoshinoBot)
可以去[SchaleDB](https://lonqie.github.io/SchaleDB/)抓
一样支持，希望能维护（赞）

**Comment by lgc2333** [comment]
> 国际服的数据的话参考[Hoshino的BA插件](https://github.com/Cosmos01/Blue_Archive_HoshinoBot) 可以去[SchaleDB](https://lonqie.github.io/SchaleDB/)抓 一样支持，希望能维护（赞）

我会慢慢写，把数据源全换到SchaleDB！

**Comment by lgc2333** [comment]
如有更多功能需求，请积极去 #8 提！
