### ISSUE TITLE
菜单无法显示该插件

### ISSUE THREAD

**Issue by CUZNIL** [lgc2333/nonebot-plugin-bawiki#21]
理论上[nonebot-plugin-bawiki](https://github.com/lgc2333/nonebot-plugin-bawiki)是已经写好了[picmenu](https://github.com/lgc2333/nonebot-plugin-bawiki/blob/master/nonebot_plugin_bawiki/__init__.py)的，所以能正常使用就能触发picmenu
但是尝试`菜单`时找不到该插件
![image](https://user-images.githubusercontent.com/76582404/218137308-4c326b39-73e7-400b-a96b-4aabcfb827f8.png)
尝试`菜单 BAWiki`时控制台报错(BAWiki是这个插件在它的[__init__.py](https://github.com/lgc2333/nonebot-plugin-bawiki/blob/master/nonebot_plugin_bawiki/__init__.py)里设置的插件名)
![WE$0L_}TIDE3R8T J{35WD9](https://user-images.githubusercontent.com/76582404/218137812-967b2465-34d3-4d71-ab29-b93934d9c54d.png)
最后尝试从json文件添加菜单，直接使用了[参考的格式](https://github.com/hamo-reid/nonebot_plugin_PicMenu#2%E4%BB%8Ejson%E6%96%87%E4%BB%B6%E6%B7%BB%E5%8A%A0%E8%8F%9C%E5%8D%95)。
![image](https://user-images.githubusercontent.com/76582404/218139334-e15f23c4-d594-445d-b0b7-53798c2315c7.png)
这是添加文件的位置，menu_config/menus文件夹是安装插件后自动生成的，所以应该不存在说放置错误。
![image](https://user-images.githubusercontent.com/76582404/218139467-618c9051-8819-485c-bcbc-428ef3c41267.png)
之所以说那么多，那自然是也报错了。当我尝试`菜单`时依旧看不到配置的文件
![image](https://user-images.githubusercontent.com/76582404/218140407-01ea3ead-7b2c-4942-998b-0c54e8def033.png)
以下是我看到的完整日志(从bot启动开始)
![GR6JBD6@MVZP7LZFIN))WCK](https://user-images.githubusercontent.com/76582404/218140585-21ed9590-ec05-482d-b913-f6ed96d15542.png)

我的nonebot是由[云崽bot](https://gitee.com/Le-niao/Yunzai-Bot)的[py插件](https://gitee.com/realhuhu/py-plugin)内置的，安装nonebot插件使用的是[时雨](https://trss-script.vercel.app/Install/Arch_Linux.html)的云崽脚本。云崽所处环境应该是[MTArch](https://trss-script.vercel.app/Install/MTArch.html)
`bash <(curl -L gitee.com/TimeRainStarSky/TRSS_Yunzai/raw/main/Install.sh)`
俩个nonebot插件的安装过程如下
![image](https://user-images.githubusercontent.com/76582404/218142848-cfbc2383-1466-48a5-a2f6-eb40e087d507.png)

如果还有别的解决问题需要的内容的话请指导我提供 谢谢
因为正常写json也无法触发预期的反应，所以我在隔壁[PicMenu](https://github.com/hamo-reid/nonebot_plugin_PicMenu)提交了一样的[issue](https://github.com/hamo-reid/nonebot_plugin_PicMenu/issues/18)

**Comment by lgc2333** [comment]
应该不是我这边的问题，可以装其他插件试试看显不显示菜单，我先close掉issue吧，如果有别的信息可以接着回复

**Comment by CUZNIL** [comment]
> 应该不是我这边的问题，可以装其他插件试试看显不显示菜单，我先close掉issue吧，如果有别的信息可以接着回复

OKK

**Comment by CUZNIL** [comment]
> 应该不是我这边的问题，可以装其他插件试试看显不显示菜单，我先close掉issue吧，如果有别的信息可以接着回复

 云崽那边的py插件更新解决了，现在能用了ww

![WSTGUJ7} $@59TRZ_Y2B)2J](https://user-images.githubusercontent.com/76582404/226564605-772eeb17-c00a-4bea-a382-16764689d25d.gif)

![MNNA`UKV EX93WEX2C) 5MG](https://user-images.githubusercontent.com/76582404/226564633-53dcecd2-383a-4aba-896d-cec5d906a2f5.gif)
