### ISSUE TITLE
不知为何只有花绘的角评出不来

### ISSUE THREAD

**Issue by Ctumille** [lgc2333/nonebot-plugin-bawiki#22]
如题，由于没有任何报错以及消息，无法提供除了聊天截图外的其他参考。如果开发者自己无法复现该问题那可能只能放弃排查了。
注：其他角色都可以正常返回，圣诞花绘都可以正常得到结果，只有花绘本人不行
![bug](https://user-images.githubusercontent.com/7392476/224468192-54b3f241-c1f4-4aa7-89ce-41d26754b1c4.png)

**Comment by lgc2333** [comment]
https://github.com/lgc2333/bawiki-data/commit/2f12ee2feb806da9ec3931d112012ac6f5ad8c23
清空缓存再尝试一下

**Comment by lgc2333** [comment]
如果有兴趣，欢迎来参与插件数据源贡献！现在数据源有段年久失修（期待你来（（（（我是大懒狗）

**Comment by Ctumille** [comment]
> 如果有兴趣，欢迎来参与插件数据源贡献！现在数据源有点年久失修（期待你来（（（（我是大懒狗）

问题解决了！谢谢！（我主要是插件的使用者，原因我也是懒狗，不过非常谢谢您）
