### ISSUE TITLE
Socks5代理支持？

### ISSUE THREAD

**Issue by TechOtakupoi233** [lgc2333/nonebot-plugin-bawiki#23]
这个插件和另一个搜图插件共用了一个`PROXY`变量，我也确认我安装了`aiohttp_socks`，但是这两个插件好像都会在使用socks5代理时出错...
![image](https://user-images.githubusercontent.com/36725374/227085463-a5d91646-faed-483b-b9ff-0daed82029d4.png)
![image](https://user-images.githubusercontent.com/36725374/227085340-adb3cd6a-9759-4e3e-9d86-34ac3ce53bb4.png)
同样的代理在Pixivbot中倒是运行正常的。

**Comment by lgc2333** [comment]
建议不用socks

**Comment by TechOtakupoi233** [comment]
> 建议不用socks

那有没有办法可以单独对此插件禁用代理？

**Comment by lgc2333** [comment]
> > 建议不用socks
> 
> 那有没有办法可以单独对此插件禁用代理？

暂时不行

话说为什么不用http代理

**Comment by TechOtakupoi233** [comment]
> > > 建议不用socks
> > 
> > 
> > 那有没有办法可以单独对此插件禁用代理？
> 
> 暂时不行
> 
> 话说为什么不用http代理

因为我就只装了ss-libev，想着一般也够用...
而且听说socks5性能好一点？
