### ISSUE TITLE
出现了bug请教一下

### ISSUE THREAD

**Issue by Rod-fish** [lgc2333/nonebot-plugin-bawiki#24]
因为这个网站http://schale.lgc2333.top/
我实在是访问不了，所以我将const内文件MIRROR_SCHALE_URL改成了
https://schaledb.brightsu.cn/
当然改成 https://lonqie.github.io/SchaleDB 或者 https://schale.gg/ 也可以用，但是图片输出会变成这个

![2058793645-645199264-4CA23F8B21C14A41CC86E327DAFDBEA1](https://user-images.githubusercontent.com/108643053/227674874-1ffe1311-e1ce-4d96-8091-08e920feeef3.png)

这里会有个更新日志去不掉，大佬能看看有办法吗

**Comment by lgc2333** [comment]
我的schaledb页面自己改过
https://github.com/lgc2333/SchaleDB/commit/4c237cfbcbb06ea286cdba55d3860928926a9e4c#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R32

**Comment by lgc2333** [comment]
如果有国内方便访问的网站托管服务可以告诉我，最好支持git

**Comment by lgc2333** [comment]
目前用的是vercel托管，绑的自己域名
