### ISSUE TITLE
ba千里眼 只显示4/11-4/18的卡池

### ISSUE THREAD

**Issue by CUZNIL** [lgc2333/nonebot-plugin-bawiki#25]
![NT9YJ{UR%U9IV7A8S38T{P](https://user-images.githubusercontent.com/76582404/229850258-732c0fdd-1fcb-40da-8d65-41ab5276c20e.png)
很奇怪，我不知道该提供什么日志。
插件是最新版本。

**Comment by lgc2333** [comment]
使用方法：https://github.com/lgc2333/nonebot-plugin-bawiki/blob/master/nonebot_plugin_bawiki/__init__.py#L188

（现在数据源有点旧了，诚邀维护者）

**Comment by lgc2333** [comment]
![TOVS}3GDLS66U(3Z _`QC3H](https://user-images.githubusercontent.com/59048777/229854278-c28d2c7f-c565-4391-9d2c-416de9dc75c0.PNG)


使用例

![image](https://user-images.githubusercontent.com/59048777/229854171-b444ad2d-b97a-42a2-a18b-01e50057bf07.png)

**Comment by CUZNIL** [comment]
> ![TOVS}3GDLS66U(3Z _`QC3H](https://user-images.githubusercontent.com/59048777/229854278-c28d2c7f-c565-4391-9d2c-416de9dc75c0.PNG)
> 
> 使用例
> 
> ![image](https://user-images.githubusercontent.com/59048777/229854171-b444ad2d-b97a-42a2-a18b-01e50057bf07.png)

多谢！

![TJNBKXMQQO{_$DL798%3C)9](https://user-images.githubusercontent.com/76582404/230008473-6170c0c4-ba30-47a4-b789-0587b2fddc98.gif)
