### ISSUE TITLE
ba漫画获取报错

### ISSUE THREAD

**Issue by Rod-fish** [lgc2333/nonebot-plugin-bawiki#46]
0.8.6测试了一下别的问题都正常了，但是现在ba漫画获取还是会报错，目前就成功过一次其他全部报错无法获取

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/108643053/ae37523b-69cc-4751-abc6-50adf2f4335c)

然后就是bawiki绘图截图太快导致数据还没加载到就截图了，倒也不是大问题，有时候出来有时候又好了就很奇怪
![fd43e70cfb26852053c358d1c8787622_720](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/108643053/f829b50e-516a-4c83-8bdf-d22b72333087)

**Comment by lgc2333** [comment]
bawiki截图我也不知道什么情况（

**Comment by lgc2333** [comment]
漫画报错真的很奇怪，我这边正常，试进禁虚拟环境 `pip install beautifulsoup4 -U`
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-bawiki/assets/59048777/ba970bd4-9e45-45ff-a543-9a8928258ebb)

**Comment by lgc2333** [comment]
尝试 0.9.0 版本
