### ISSUE TITLE
截图失败

### ISSUE THREAD

**Issue by liuzj288** [lgc2333/nonebot-plugin-bawiki#9]
![image](https://user-images.githubusercontent.com/13833404/189488225-4d53f5f5-b3d9-4201-badf-73ea0bee044c.png)
![image](https://user-images.githubusercontent.com/13833404/189488235-a1f3c93d-12f8-4eac-b27b-c365bf892ff8.png)

**Comment by lgc2333** [comment]
寄 难受啊草

**Comment by lgc2333** [comment]
又出玄学问题

**Comment by lgc2333** [comment]
你试试手动用浏览器访问这个链接，不挂任何代理

**Comment by liuzj288** [comment]
> 你试试手动用浏览器访问这个链接，不挂任何代理

截的github啊，那出错很正常了

**Comment by liuzj288** [comment]
我是不是可以把SchaleDB本地化的话，插件可以做个自定义SchaleDB的网址

**Comment by lgc2333** [comment]
我用的是我自己的schaleDB的fork（因为我魔改了student.html）
要不我加个proxy配置

**Comment by lgc2333** [comment]
唉 尝试搞了一下 脑壳疼 还是技不如人
如果给htmlrender插件弄proxy的话会出玄学bug
如果自己再弄个弄playwright的话资源开销太大~~，而且没有现成的轮子方便~~
之前有把schaledb克隆到本地的想法，但是感觉仓库太大就打消了
自己画图太麻烦，而且我真的不会设计图片排板

技不如人啊

**Comment by lgc2333** [comment]
呜呜呜如果谁会设计下图片排板什么的我可以尝试一下pil画图quq
